# Generated by Django 5.1.4 on 2025-01-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_listing_outdoor_square_meters_listing_total_beds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('can_have_beds', models.BooleanField(default=False, verbose_name='Può contenere letti')),
            ],
            options={
                'verbose_name': 'Tipo Stanza',
                'verbose_name_plural': 'Tipi Stanza',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Metri quadri')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Piano')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='listings.listing', verbose_name='Appartamento')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.roomtype', verbose_name='Tipo stanza')),
            ],
            options={
                'verbose_name': 'Stanza',
                'verbose_name_plural': 'Stanze',
                'ordering': ['order'],
            },
        ),
    ]
