# Generated by Django 5.1.4 on 2025-03-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_description_en_room_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name_it',
        ),
    ]
