# Generated by Django 5.1.4 on 2025-01-16 09:24

import django.db.models.deletion
import icons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria Icona',
                'verbose_name_plural': 'Categorie Icone',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_type', models.CharField(choices=[('fa', 'Font Awesome'), ('custom', 'Icona Personalizzata')], default='fa', max_length=10)),
                ('fa_class', models.CharField(blank=True, help_text='Classe Font Awesome (es. fa-home)', max_length=50)),
                ('custom_icon', models.FileField(blank=True, help_text='File SVG per icona personalizzata', upload_to='icons/', validators=[icons.models.validate_svg])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='icons.iconcategory')),
            ],
            options={
                'verbose_name': 'Icona',
                'verbose_name_plural': 'Icone',
                'ordering': ['category', 'name'],
            },
        ),
    ]
