# Generated by Django 5.1.4 on 2025-01-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('active', 'Attivo'), ('inactive', 'Non attivo')], default='draft', max_length=20, verbose_name='Stato')),
                ('max_guests', models.IntegerField(verbose_name='Numero massimo ospiti')),
                ('bedrooms', models.IntegerField(verbose_name='Numero camere da letto')),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Numero bagni')),
                ('address', models.CharField(max_length=255, verbose_name='Indirizzo')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('zone', models.CharField(max_length=100, verbose_name='Zona')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo base per notte')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo pulizie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annuncio',
                'verbose_name_plural': 'Annunci',
            },
        ),
    ]
