# Generated by Django 5.1.4 on 2025-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='outdoor_square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Metri Quadri Esterni'),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='Totale letti'),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_sleeps',
            field=models.PositiveIntegerField(default=0, verbose_name='Totale posti letto'),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_square_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Metri Quadri Totali'),
        ),
    ]
