# Generated by Django 5.1.4 on 2025-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listingrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titolo')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='È consentito')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='Orario inizio')),
                ('time_to', models.TimeField(blank=True, null=True, verbose_name='Orario fine')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Regola obbligatoria')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Regola di Sistema',
                'verbose_name_plural': 'Regole di Sistema',
                'ordering': ['order'],
            },
        ),
    ]
