# Generated by Django 5.1.4 on 2025-03-18 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_systemrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingrule',
            name='listing',
        ),
        migrations.DeleteModel(
            name='SystemRule',
        ),
        migrations.AddField(
            model_name='listing',
            name='allow_parties',
            field=models.BooleanField(default=False, verbose_name='Feste consentite'),
        ),
        migrations.AddField(
            model_name='listing',
            name='allow_photos',
            field=models.BooleanField(default=True, verbose_name='Foto/Video consentiti'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkin_from',
            field=models.TimeField(default=datetime.time(15, 0), verbose_name='Check-in dalle'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkin_notes',
            field=models.TextField(blank=True, verbose_name='Note check-in'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkin_to',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Check-in fino alle'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkout_notes',
            field=models.TextField(blank=True, verbose_name='Note check-out'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkout_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Check-out entro le'),
        ),
        migrations.AddField(
            model_name='listing',
            name='parties_notes',
            field=models.TextField(blank=True, verbose_name='Note feste'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photos_notes',
            field=models.TextField(blank=True, verbose_name='Note foto/video'),
        ),
        migrations.DeleteModel(
            name='ListingRule',
        ),
    ]
