# Generated by Django 5.1.4 on 2025-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_allow_smoking_listing_smoking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='checkin_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Note check-in'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkin_notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='Note check-in'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkin_notes_it',
            field=models.TextField(blank=True, null=True, verbose_name='Note check-in'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkout_notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Note check-out'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkout_notes_es',
            field=models.TextField(blank=True, null=True, verbose_name='Note check-out'),
        ),
        migrations.AddField(
            model_name='listing',
            name='checkout_notes_it',
            field=models.TextField(blank=True, null=True, verbose_name='Note check-out'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titolo'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Titolo'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='Titolo'),
        ),
    ]
