# Generated by Django 5.2.6 on 2025-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es. "Appartamenti Centro", "Suite Familiari"', max_length=200, verbose_name='Nome del gruppo')),
                ('description', models.TextField(blank=True, help_text='Descrizione del gruppo di appartamenti', verbose_name='Descrizione')),
                ('is_active', models.BooleanField(default=True, help_text='Se disattivo, questo gruppo non apparirà nelle ricerche combinate', verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listings', models.ManyToManyField(help_text='Seleziona gli appartamenti che possono essere prenotati insieme', to='listings.listing', verbose_name='Appartamenti')),
            ],
            options={
                'verbose_name': 'Gruppo di Appartamenti',
                'verbose_name_plural': 'Gruppi di Appartamenti',
                'ordering': ['name'],
            },
        ),
    ]
