# Generated by Django 5.2.7 on 2025-11-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listinggroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200, verbose_name='Nome recensore')),
                ('reviewer_location', models.CharField(blank=True, help_text='Es: "Roma, Italia"', max_length=200, verbose_name='Località recensore')),
                ('reviewer_avatar_url', models.URLField(blank=True, help_text='URL immagine profilo', verbose_name='Avatar recensore')),
                ('review_date', models.DateField(verbose_name='Data recensione')),
                ('stay_date', models.DateField(blank=True, help_text='Data del soggiorno recensito', null=True, verbose_name='Data soggiorno')),
                ('review_text', models.TextField(verbose_name='Testo recensione')),
                ('host_response', models.TextField(blank=True, help_text="Risposta dell'host alla recensione", verbose_name='Risposta host')),
                ('host_response_date', models.DateField(blank=True, null=True, verbose_name='Data risposta host')),
                ('overall_rating', models.DecimalField(decimal_places=1, help_text='Da 1.0 a 5.0', max_digits=2, verbose_name='Valutazione complessiva')),
                ('cleanliness_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Da 1.0 a 5.0', max_digits=2, null=True, verbose_name='Pulizia')),
                ('accuracy_rating', models.DecimalField(blank=True, decimal_places=1, help_text="Corrispondenza con l'annuncio (1.0-5.0)", max_digits=2, null=True, verbose_name='Precisione')),
                ('checkin_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Facilità di check-in (1.0-5.0)', max_digits=2, null=True, verbose_name='Check-in')),
                ('communication_rating', models.DecimalField(blank=True, decimal_places=1, help_text="Comunicazione con l'host (1.0-5.0)", max_digits=2, null=True, verbose_name='Comunicazione')),
                ('location_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Qualità della posizione (1.0-5.0)', max_digits=2, null=True, verbose_name='Posizione')),
                ('value_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Valore per il prezzo pagato (1.0-5.0)', max_digits=2, null=True, verbose_name='Rapporto qualità-prezzo')),
                ('airbnb_review_id', models.CharField(blank=True, help_text='ID univoco della recensione su Airbnb (per evitare duplicati)', max_length=100, null=True, unique=True, verbose_name='ID Recensione Airbnb')),
                ('airbnb_listing_url', models.URLField(blank=True, help_text='URL della pagina Airbnb da cui è stata importata', verbose_name='URL Listing Airbnb')),
                ('is_verified', models.BooleanField(default=False, help_text='Recensione verificata da soggiorno effettivo', verbose_name='Verificata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aggiornamento')),
                ('last_synced', models.DateTimeField(blank=True, help_text="Data dell'ultima sincronizzazione automatica", null=True, verbose_name='Ultima sincronizzazione')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listing', verbose_name='Appartamento')),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
                'ordering': ['-review_date', '-created_at'],
                'indexes': [models.Index(fields=['listing', '-review_date'], name='listings_re_listing_1e9246_idx'), models.Index(fields=['airbnb_review_id'], name='listings_re_airbnb__a3ba9e_idx')],
            },
        ),
    ]
