# Generated by Django 5.2.7 on 2025-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='airbnb_listing_url',
            field=models.URLField(blank=True, help_text='URL della pagina Airbnb per sincronizzazione automatica recensioni (es: https://www.airbnb.it/rooms/12345678)', null=True, verbose_name='URL Listing Airbnb'),
        ),
    ]
