# Generated by Django 5.2.7 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_airbnb_listing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='airbnb_reviews_last_synced',
            field=models.DateTimeField(blank=True, help_text="Data e ora dell'ultima sincronizzazione recensioni Airbnb", null=True, verbose_name='Ultima Sincronizzazione Recensioni'),
        ),
    ]
