# Generated by Django 5.2.7 on 2025-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listing_airbnb_reviews_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='airbnb_accuracy_avg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Media aggregata da Airbnb per la categoria Precisione', max_digits=3, null=True, verbose_name='Media Precisione (Airbnb)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='airbnb_checkin_avg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Media aggregata da Airbnb per la categoria Check-in', max_digits=3, null=True, verbose_name='Media Check-in (Airbnb)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='airbnb_cleanliness_avg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Media aggregata da Airbnb per la categoria Pulizia', max_digits=3, null=True, verbose_name='Media Pulizia (Airbnb)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='airbnb_communication_avg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Media aggregata da Airbnb per la categoria Comunicazione', max_digits=3, null=True, verbose_name='Media Comunicazione (Airbnb)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='airbnb_location_avg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Media aggregata da Airbnb per la categoria Posizione', max_digits=3, null=True, verbose_name='Media Posizione (Airbnb)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='airbnb_value_avg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Media aggregata da Airbnb per la categoria Rapporto Qualità-Prezzo', max_digits=3, null=True, verbose_name='Media Rapporto Qualità-Prezzo (Airbnb)'),
        ),
    ]
