# Generated by Django 5.1.4 on 2025-01-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0005_listing_extra_guest_fee_listing_gap_between_bookings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOutRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('no_checkin', 'No Check-in'), ('no_checkout', 'No Check-out')], max_length=20)),
                ('recurrence_type', models.CharField(choices=[('specific_date', 'Data Specifica'), ('weekly', 'Settimanale')], max_length=20)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Lunedì, 6=Domenica', null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkinout_rules', to='listings.listing')),
            ],
            options={
                'ordering': ['rule_type', 'recurrence_type'],
            },
        ),
        migrations.CreateModel(
            name='ClosureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_external_booking', models.BooleanField(default=False, help_text='Se true, indica prenotazione da altra piattaforma')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_rules', to='listings.listing')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_nights', models.PositiveIntegerField(blank=True, help_text='Soggiorno minimo per questo periodo', null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='listings.listing')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
