# Generated by Django 5.1.13 on 2025-11-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_rules', '0001_initial'),
        ('listings', '0012_listinggroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinoutrule',
            options={'ordering': ['rule_type', 'recurrence_type'], 'verbose_name': 'Regola Check-in/Check-out', 'verbose_name_plural': 'Regole Check-in/Check-out'},
        ),
        migrations.AlterModelOptions(
            name='closurerule',
            options={'ordering': ['start_date'], 'verbose_name': 'Regola di Chiusura', 'verbose_name_plural': 'Regole di Chiusura'},
        ),
        migrations.AlterModelOptions(
            name='pricerule',
            options={'ordering': ['-start_date'], 'verbose_name': 'Regola Prezzo', 'verbose_name_plural': 'Regole Prezzo'},
        ),
        migrations.AlterField(
            model_name='checkinoutrule',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Lunedì, 6=Domenica (usato solo se ricorrenza = "Settimanale")', null=True, verbose_name='Giorno settimana'),
        ),
        migrations.AlterField(
            model_name='checkinoutrule',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkinout_rules', to='listings.listing', verbose_name='Appartamento'),
        ),
        migrations.AlterField(
            model_name='checkinoutrule',
            name='recurrence_type',
            field=models.CharField(choices=[('specific_date', 'Data Specifica'), ('weekly', 'Settimanale')], max_length=20, verbose_name='Tipo ricorrenza'),
        ),
        migrations.AlterField(
            model_name='checkinoutrule',
            name='rule_type',
            field=models.CharField(choices=[('no_checkin', 'No Check-in'), ('no_checkout', 'No Check-out')], max_length=20, verbose_name='Tipo regola'),
        ),
        migrations.AlterField(
            model_name='checkinoutrule',
            name='specific_date',
            field=models.DateField(blank=True, help_text='Usato solo se ricorrenza = "Data Specifica"', null=True, verbose_name='Data specifica'),
        ),
        migrations.AlterField(
            model_name='closurerule',
            name='end_date',
            field=models.DateField(verbose_name='Data fine'),
        ),
        migrations.AlterField(
            model_name='closurerule',
            name='is_external_booking',
            field=models.BooleanField(default=False, help_text='Se true, indica prenotazione da altra piattaforma (Airbnb, Booking.com, ecc.)', verbose_name='Prenotazione esterna'),
        ),
        migrations.AlterField(
            model_name='closurerule',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_rules', to='listings.listing', verbose_name='Appartamento'),
        ),
        migrations.AlterField(
            model_name='closurerule',
            name='reason',
            field=models.CharField(blank=True, help_text='Es: "Manutenzione", "Chiusura stagionale"', max_length=200, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='closurerule',
            name='start_date',
            field=models.DateField(verbose_name='Data inizio'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='end_date',
            field=models.DateField(verbose_name='Data fine'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='listings.listing', verbose_name='Appartamento'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='min_nights',
            field=models.PositiveIntegerField(blank=True, help_text='Soggiorno minimo per questo periodo', null=True, verbose_name='Soggiorno minimo'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo per notte'),
        ),
        migrations.AlterField(
            model_name='pricerule',
            name='start_date',
            field=models.DateField(verbose_name='Data inizio'),
        ),
        migrations.CreateModel(
            name='ExternalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es: "Airbnb Roma Centro", "Booking.com Appartamento 1"', max_length=200, verbose_name='Nome calendario')),
                ('provider', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('expedia', 'Expedia'), ('other', 'Altro')], default='other', max_length=50, verbose_name='Provider')),
                ('ical_url', models.URLField(help_text='URL del calendario iCal da sincronizzare (es: https://calendar.airbnb.com/ical/.../calendar.ics)', verbose_name='URL iCal')),
                ('is_active', models.BooleanField(default=True, help_text='Se disattivato, questo calendario non verrà sincronizzato', verbose_name='Attivo')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, help_text='Ogni quanti minuti sincronizzare questo calendario', verbose_name='Intervallo sincronizzazione (minuti)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Ultima sincronizzazione')),
                ('last_sync_status', models.CharField(choices=[('success', 'Successo'), ('error', 'Errore'), ('pending', 'In attesa')], default='pending', max_length=20, verbose_name='Stato ultima sincronizzazione')),
                ('last_sync_error', models.TextField(blank=True, help_text="Messaggio di errore dell'ultima sincronizzazione, se presente", verbose_name='Ultimo errore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_calendars', to='listings.listing', verbose_name='Appartamento')),
            ],
            options={
                'verbose_name': 'Calendario Esterno',
                'verbose_name_plural': 'Calendari Esterni',
                'ordering': ['listing', 'name'],
            },
        ),
    ]
