# Generated by Django 5.1.4 on 2025-01-15 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.ImageField(upload_to='listings/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/%Y/%m/')),
                ('medium', models.ImageField(blank=True, null=True, upload_to='listings/medium/%Y/%m/')),
                ('large', models.ImageField(blank=True, null=True, upload_to='listings/large/%Y/%m/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='images_imag_content_0cb5ba_idx')],
            },
        ),
    ]
