# Generated by Django 5.1.4 on 2025-01-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('listings', '0004_alter_listing_bedrooms'),
        ('rooms', '0002_remove_room_floor_alter_room_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_content_0cb5ba_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='image',
            name='large',
        ),
        migrations.RemoveField(
            model_name='image',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='image',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='image',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room'),
        ),
    ]
