"""
Django settings for Rhome_book project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config, Csv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print("BASE_DIR:", BASE_DIR) 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from .env file using python-decouple
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Allowed hosts - should be configured in .env for production
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',  # Richiesto da allauth - deve essere PRIMA di modeltranslation
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'listings.apps.ListingsConfig',
    'amenities',
    'beds',
    'rooms.apps.RoomsConfig',
    'images',
    'icons.apps.IconsConfig',
    'calendar_rules',
    'rest_framework',
    'translations',
    'bookings.apps.BookingsConfig',
    'users.apps.UsersConfig',
    'admin_panel',  # Pannello admin esterno
    # Django Allauth per social login
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Aggiungi dopo SessionMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Richiesto da django-allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Rhome_book.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS':[os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,  # Ripristinato - necessario per template Django standard
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Rhome_book.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Cache configuration
# Per produzione, usare Redis o Memcached
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minuti default
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Debug calendario - abilita logging dettagliato (disabilitare in produzione)
DEBUG_CALENDAR = config('DEBUG_CALENDAR', default=False, cast=bool)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
# Lingue supportate
LANGUAGES = [
    ('it', 'Italiano'),
    ('en', 'English'),
    ('es', 'Español'),
    # Puoi aggiungerne altre
]
LANGUAGE_CODE = 'it'

# Changed from UTC to Europe/Rome for Italian booking system
# This ensures check-in/check-out times are correct with DST
TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True

# Charset configuration
DEFAULT_CHARSET = 'utf-8'
FILE_CHARSET = 'utf-8'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Aggiungi queste impostazioni
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # cartella dove verranno raccolti i file statici
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  # cartella dove metterai i tuoi file statici
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Definisce l'URL base per i file media
MEDIA_URL = '/media/'

# Definisce il percorso assoluto dove vengono salvati i file
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print("Template dirs:", TEMPLATES[0]['DIRS'])
# Attiva l'internazionalizzazione
USE_I18N = True

# Attiva la localizzazione
USE_L10N = True

# Cartella dove verranno salvati i file di traduzione
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Modeltranslation: Configurazione per evitare errori nell'admin
# Disabilita la traduzione automatica - solo i modelli esplicitamente registrati verranno tradotti
MODELTRANSLATION_AUTO_POPULATE = False
MODELTRANSLATION_FALLBACK_LANGUAGES = ('it',)

# Escludi esplicitamente le app di sistema dalla traduzione
MODELTRANSLATION_EXCLUDED_APPS = [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
]

# Django Allauth Configuration
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Settings
# Nuove impostazioni (django-allauth >= 0.57.0)
ACCOUNT_LOGIN_METHODS = {'email', 'username'}  # Permette login con username o email
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # Campi obbligatori per signup
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # 'mandatory', 'optional', o 'none'
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/m'  # 5 tentativi per minuto
}

# Impostazioni deprecate (mantenute per compatibilità, verranno rimosse in futuro)
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # DEPRECATO - usa ACCOUNT_LOGIN_METHODS
# ACCOUNT_EMAIL_REQUIRED = True  # DEPRECATO - usa ACCOUNT_SIGNUP_FIELDS
# ACCOUNT_USERNAME_REQUIRED = True  # DEPRECATO - usa ACCOUNT_SIGNUP_FIELDS
# ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False  # DEPRECATO - usa ACCOUNT_SIGNUP_FIELDS
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5  # DEPRECATO - usa ACCOUNT_RATE_LIMITS
# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # DEPRECATO - usa ACCOUNT_RATE_LIMITS

LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Social Account Settings
SOCIALACCOUNT_LOGIN_ON_GET = True  # Permette login social con GET
SOCIALACCOUNT_AUTO_SIGNUP = True  # Crea automaticamente l'account al login social

# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'it_IT',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v18.0',
    }
}



# Impostazioni per la sessione
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Configurazione logging per debug calendario
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'calendar_debug': {
            'format': '\033[1;32m[CALENDAR DEBUG]\033[0m {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'calendar_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'calendar_debug',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'calendar_debug.log',
            'formatter': 'verbose',
            'maxBytes': 5_000_000,  # 5MB
            'backupCount': 3,  # Keep 3 backup files
        },
    },
    'loggers': {
        'calendar_debug': {
            'handlers': ['calendar_console', 'file'],
            'level': 'INFO',
            'propagate': False,  # Evita duplicazione
        },
        'listings.services.review_sync': {
            'handlers': ['console'],
            'level': 'INFO',  # Mostra INFO e superiori
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',  # Riduci il rumore di Django
            'propagate': False,
        },
    },
}

# Increase max number of fields for admin forms with many inlines
# (beds, photos, price rules, amenities, etc.)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}