# Generated by Django 5.1.4 on 2025-01-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Categoria')),
                ('icon', models.CharField(blank=True, help_text='Nome icona FontAwesome', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Ordine di visualizzazione')),
            ],
            options={
                'verbose_name': 'Categoria Servizi',
                'verbose_name_plural': 'Categorie Servizi',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(blank=True, help_text='Nome icona FontAwesome', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Breve descrizione del servizio', verbose_name='Descrizione')),
                ('is_popular', models.BooleanField(default=False, help_text='Indica se è un servizio molto richiesto', verbose_name='Popolare')),
                ('order', models.IntegerField(default=0, help_text='Ordine di visualizzazione')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='amenities.amenitycategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
