# Generated by Django 5.1.4 on 2025-01-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='amenitycategory',
            name='icon',
        ),
    ]
