# Generated by Django 5.1.4 on 2025-01-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0002_remove_amenity_icon_remove_amenitycategory_icon'),
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities', to='icons.icon', verbose_name='Icona'),
        ),
    ]
