# Generated by Django 5.1.4 on 2025-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0003_amenity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='description_en',
            field=models.TextField(blank=True, help_text='Breve descrizione del servizio', null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='description_es',
            field=models.TextField(blank=True, help_text='Breve descrizione del servizio', null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='description_it',
            field=models.TextField(blank=True, help_text='Breve descrizione del servizio', null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
