# Generated by Django 5.1.4 on 2025-03-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0004_amenity_description_en_amenity_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitycategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome Categoria'),
        ),
        migrations.AddField(
            model_name='amenitycategory',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome Categoria'),
        ),
        migrations.AddField(
            model_name='amenitycategory',
            name='name_it',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome Categoria'),
        ),
    ]
