# Generated by Django 5.1.4 on 2025-01-14 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_listing_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo letto')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Tipo di letto',
                'verbose_name_plural': 'Tipi di letto',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Es: Camera matrimoniale, Soggiorno', max_length=100, verbose_name='Nome stanza')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantità')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='listings.listing')),
                ('bed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beds.bedtype', verbose_name='Tipo letto')),
            ],
            options={
                'verbose_name': 'Letto',
                'verbose_name_plural': 'Letti',
            },
        ),
    ]
