# Generated by Django 5.1.4 on 2025-01-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_alter_bed_options_alter_bedtype_options_and_more'),
        ('listings', '0002_listing_amenities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'verbose_name': 'Letto', 'verbose_name_plural': 'Letti'},
        ),
        migrations.AddField(
            model_name='bed',
            name='bed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beds.bedtype', verbose_name='Tipo letto'),
        ),
        migrations.AddField(
            model_name='bed',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='listings.listing', verbose_name='Appartamento'),
        ),
        migrations.AddField(
            model_name='bed',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantità'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_name',
            field=models.CharField(blank=True, help_text='Es: Camera matrimoniale, Soggiorno', max_length=100, null=True, verbose_name='Nome stanza'),
        ),
    ]
