# Generated by Django 5.1.4 on 2025-01-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0003_alter_bed_options_bed_bed_type_bed_listing_and_more'),
        ('listings', '0003_listing_outdoor_square_meters_listing_total_beds_and_more'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='room_name',
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='rooms.room', verbose_name='Stanza'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='beds.bedtype', verbose_name='Tipo letto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bed',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='listings.listing', verbose_name='Appartamento'),
        ),
    ]
