# Generated by Django 5.2.6 on 2025-09-25 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_base_price_per_night_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_guests', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_nights', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cleaning_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('extra_guest_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('confirmed', 'Confermata'), ('cancelled', 'Cancellata'), ('completed', 'Completata'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'In Attesa'), ('partial', 'Parziale'), ('paid', 'Pagato'), ('refunded', 'Rimborsato')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('host_notes', models.TextField(blank=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prenotazione Combinata',
                'verbose_name_plural': 'Prenotazioni Combinate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='multi_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_bookings', to='bookings.multibooking'),
        ),
    ]
