# Generated by Django 5.1.13 on 2025-11-13 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_multibooking_booking_multi_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data invio')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Data lettura')),
                ('is_read', models.BooleanField(default=False, verbose_name='Letto')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.booking')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messaggio',
                'verbose_name_plural': 'Messaggi',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='bookings_me_booking_59dff7_idx'), models.Index(fields=['recipient', 'is_read'], name='bookings_me_recipie_2e52da_idx')],
            },
        ),
    ]
